[font]
size = 14.0

[font.bold]
family = 'JetBrains Mono'
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.90
padding = {x=10, y=10}
dynamic_padding = true

[cursor]
style = {shape="beam", blinking="never"}
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.7
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.6
# Limits how the cursor size may change
smooth_motion_max_stretch_x = 2.0
smooth_motion_max_stretch_y = 2.0

# Override "block" cursor if you don't like how it looks in this fork
# I prefer "underline"
block_replace_shape = "beam"

# colors (miasma) https://github.com/xero/miasma.nvim
[colors]
indexed_colors = [{ index = 16, color = "0x222222"}]

# Primary colors
[colors.primary]
background = "#101010"
foreground = "#F9F9E0"

# Normal colors
[colors.normal]
black = "#212121"
red = "#EF6262"
green = "#3AA6B9"
yellow = "#EF6262"
blue = "#1D5B79"
magenta = "#FF9EAA"
cyan = "#FF9EAA"
white = "#F9F9E0"

# Bright colors
[colors.bright]
black = "#212121"
red = "#EF6262"
green = "#3AA6B9"
yellow = "#EF6262"
blue = "#1D5B79"
magenta = "#FF9EAA"
cyan = "#FF9EAA"
white = "#F9F9E0"
